// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeeProject.Models;

public partial class Company
{
    public long Id { get; set; }

    public string CompanyName { get; set; }

    public virtual ICollection<EmpJobDet> EmpJobDets { get; set; } = new List<EmpJobDet>();
}