// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeeProject.Models;

public partial class EmpJobDet
{
    public long Id { get; set; }

    public long EmpId { get; set; }

    public long? Salary { get; set; }

    public long? CompanyId { get; set; }

    public long? DesignationId { get; set; }

    public virtual Company Company { get; set; }

    public virtual Designation Designation { get; set; }

    public virtual Employee Emp { get; set; }
}