// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeeProject.Models;

public partial class EmployeeDetail
{
    public long Id { get; set; }

    public long EmpId { get; set; }

    public long? MobileNumber { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public virtual Employee Emp { get; set; }
}