// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeeProject.Models;

public partial class PivotTable
{
    public string Country { get; set; }

    public string States { get; set; }
}