// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EmployeeProject.Models;

public partial class SampleDbContext : DbContext
{
    public SampleDbContext(DbContextOptions<SampleDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<Designation> Designations { get; set; }

    public virtual DbSet<EmpJobDet> EmpJobDets { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeDetail> EmployeeDetails { get; set; }

    public virtual DbSet<PivotTable> PivotTables { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Company>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Company__3214EC07493CD311");

            entity.ToTable("Company");

            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<Designation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Designat__3214EC074389FC26");

            entity.ToTable("Designation");

            entity.Property(e => e.Designation1)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("Designation");
        });

        modelBuilder.Entity<EmpJobDet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EmpJobDe__3214EC0763C19EBB");

            entity.ToTable("EmpJobDet");

            entity.HasOne(d => d.Company).WithMany(p => p.EmpJobDets)
                .HasForeignKey(d => d.CompanyId)
                .HasConstraintName("FK__EmpJobDet__Compa__07C12930");

            entity.HasOne(d => d.Designation).WithMany(p => p.EmpJobDets)
                .HasForeignKey(d => d.DesignationId)
                .HasConstraintName("FK__EmpJobDet__Desig__60A75C0F");

            entity.HasOne(d => d.Emp).WithMany(p => p.EmpJobDets)
                .HasForeignKey(d => d.EmpId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EmpJobDet__EmpId__4E88ABD4");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC070A7FF05B");

            entity.ToTable("Employee");

            entity.Property(e => e.EmployeeName).HasMaxLength(200);
        });

        modelBuilder.Entity<EmployeeDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC0780B55655");

            entity.Property(e => e.Address).HasMaxLength(220);
            entity.Property(e => e.City).HasMaxLength(220);

            entity.HasOne(d => d.Emp).WithMany(p => p.EmployeeDetails)
                .HasForeignKey(d => d.EmpId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EmployeeD__EmpId__4D94879B");
        });

        modelBuilder.Entity<PivotTable>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("PivotTable");

            entity.Property(e => e.Country).HasMaxLength(200);
            entity.Property(e => e.States)
                .HasMaxLength(200)
                .HasColumnName("states");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}